import json
import time
import logging
from pathlib import Path
from metadata_ingestion.clients.musicbrainz_client import MusicBrainzClient

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s"
)
log = logging.getLogger(__name__)

OUTPUT_DIR = Path(__file__).parent.parent / "output"
ARTIST_METADATA_PATH = OUTPUT_DIR / "artist_metadata.json"
TRACK_METADATA_PATH = OUTPUT_DIR / "track_metadata.json"
ISRC_MAPPING_PATH = OUTPUT_DIR / "isrc_mapping.json"

RELEASES_PER_ARTIST = 5

def load_artist_metadata() -> list:
    """
    Load artist metadata generated by ingest_artist.py.
    """

    with open(ARTIST_METADATA_PATH, "r", encoding="utf-8") as file:
        return json.load(file)


def fetch_tracks(client: MusicBrainzClient, artists: list) -> list:
    """
    Fetch releases and tracks for every artist.
    """

    all_tracks = []

    for index, artist in enumerate(artists, start=1):

        artist_name = artist["artist_name"]
        artist_id = artist["artist_id"]

        log.info(
            f"[{index}/{len(artists)}] Processing {artist_name}"
        )

        try:
            releases = client.get_releases_for_artist(
                artist_id,
                limit=RELEASES_PER_ARTIST
            )

            log.info(f"Found {len(releases)} releases")

            for release in releases:

                tracks = client.get_tracks_for_release(
                    release["release_id"]
                )

                for track in tracks:

                    track["artist_id"] = artist_id
                    track["artist_name"] = artist_name
                    track["artist_country"] = artist["country"]
                    track["artist_genres"] = artist["genres"]

                    all_tracks.append(track)

        except Exception as e:
            log.warning(
                f"Failed processing {artist_name}: {e}"
            )

    return all_tracks

def save_tracks(tracks: list):
    """
    Save track metadata as JSON.
    """

    OUTPUT_DIR.mkdir(
        parents=True,
        exist_ok=True
    )

    with open(TRACK_METADATA_PATH, "w", encoding="utf-8") as file:
        json.dump(
            tracks,
            file,
            indent=4,
            ensure_ascii=False
        )

    log.info(f"Saved {len(tracks)} tracks")

def build_isrc_mapping(tracks: list):
    """
    Create an ISRC lookup dictionary.
    """

    mapping = {}

    for track in tracks:

        isrc = track.get("isrc")

        if isrc:
            mapping[isrc] = track["track_id"]

    with open(ISRC_MAPPING_PATH, "w", encoding="utf-8") as file:
        json.dump(
            mapping,
            file,
            indent=4,
            ensure_ascii=False
        )

    log.info(f"Created {len(mapping)} ISRC mappings")

def run():

    client = MusicBrainzClient()

    artists = load_artist_metadata()

    tracks = fetch_tracks(
        client,
        artists
    )

    save_tracks(tracks)

    build_isrc_mapping(tracks)


if __name__ == "__main__":
    run()

